src/paylive.Console/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using paylive.Console.DbContext;
using paylive.Console.Core;

namespace paylive.Console.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            List<Receivers> list;
            using (var live = new LiveContext())
            {
                list = live.Receivers.ToList();
            }
            return View(list);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string msg,string imno)
        {
            WebImConfig im;
            using (var live = new LiveContext())
            {
                im = live.WebImConfig.FirstOrDefault();
            }

            var body = $"UserName={im.UserName}&Msg={msg}&Receivers={imno}&ssid={im.Ssid}";
            var result = await HttpService.Post<object>(body, Config._Sendsms);
            using (var live = new LiveContext())
            {
                live.SmsQu.Add(new SmsQu()
                {
                    Msg = msg,
                    Receivers = imno,
                    Completed = result.StringBody.rc == "200",
                    AddTime = DateTime.Now
                });
                live.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Contact()
        {
            List<Receivers> list;
            using (var live = new LiveContext())
            {
                list = live.Receivers.ToList();
            }
            return View(list);
        }

        [HttpPost]
        public IActionResult Contact(string mobile, string imno)
        {
            using (var live = new LiveContext())
            {
                var rece = live.Receivers.Any(i => i.Mobile == mobile && i.ImNo == imno);
                if (!rece)
                    live.Receivers.Add(new Receivers()
                    {
                        Mobile = mobile,
                        ImNo = imno,
                        AddTime = DateTime.Now
                    });
                live.SaveChanges();
            }

            return RedirectToAction("Contact");
        }

        public IActionResult Error()
        {
            return View();
        }

        public IActionResult H5()
        {
            return View();
        }
    }
}

src/paylive.Console/Controllers/RobotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using paylive.Console.Core;
using paylive.Console.DbContext;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace paylive.Console.Controllers
{
    //飞信维持登录状态
    public class RobotController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public async Task GetSmsPwd()
        {
            await HttpService.Post<object>("uname=13718607977", Config._GetSmsPwd);
        }

        public async Task Login(string pwd)
        {
            var ret = await HttpService.Post<object>($"UserName=13718607977&Pwd={pwd}&OnlineStatus=400&AccountType=1&Ccp=", Config._Login);
            if (ret.CookieCollection.Count > 0&& ret.CookieCollection["webim_sessionid"]!=null)
            {
                var webimsessionid = ret.CookieCollection["webim_sessionid"].Value;
                using (var live = new LiveContext())
                {
                    var im = live.WebImConfig.FirstOrDefault();
                    if (im == null)
                    {
                        live.WebImConfig.Add(new WebImConfig() { UserName = "213129474", Ssid = webimsessionid });
                    }
                    else
                    {
                        im.UserName = "213129474";
                        im.Ssid = webimsessionid;
                    }
                    live.SaveChanges();
                }
                GetConnect(webimsessionid);
            }
        }

        public async Task GetConnect(string webimsessionid)
        {
            //心跳计数
            int i = 10;

            while (true)
            {
                try
                {
                    var ret = await HttpService.Post<List<ConnectBody>>($"ssid={webimsessionid}&reported=", string.Format(Config._GetConnect, i));
                    if ((ret.StringBody.rc != "305" && ret.StringBody.rc != "200") || i == 36000)
                    {
                        Core.Core.WriteTextLog("GetConnect" + webimsessionid, ret.StringBody.rc, DateTime.Now);
                        GetSmsPwd();
                        break;
                    }
                    i++;
                }
                catch (Exception ex)
                {
                    Core.Core.WriteTextLog("GetConnect" + webimsessionid, ex.Message, DateTime.Now);
                    GetSmsPwd();
                }
                Thread.Sleep(5000);
            }
        }
    }
}

src/paylive.Console/Views/Home/Contact.cshtml
@model List<paylive.Console.DbContext.Receivers>
@{
    ViewData["Title"] = "Contact";
    Layout = null;
}
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1" />
    <!-- head 中 -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>

    </title>
    <!-- body 最后 -->

</head>
<body style="text-align: center">
    <form action="@Url.Action("Contact", "Home")" method="post">
        <p>
            手机号:<input type="text" id="mobile" name="mobile" style="height: 50px; width: 100px" />
        </p>
        <p>
            飞信号:<input type="text" id="imno" name="imno" style="height: 50px; width: 100px" />
        </p>
        <p>
            <input type="submit" value="提交" />
        </p>
    </form>
    @{
        if (Model != null)
        {
            foreach (var item in Model)
            {
                <p>mobile:@(item.Mobile) | imno:@(item.ImNo)</p>
            }
        }
    }

</body>
</html>

src/paylive.Console/Views/Home/H5.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>demo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <script charset="utf-8" src="http://map.qq.com/api/js?v=2.exp"></script>
    <style type="text/css">
        html,
        body {
            height: 100%;
            margin: 0px;
            padding: 0px;
            text-align:center
        }

        #container {
            width: 100%;
            height: 100%;
        }

        body div {
            text-indent: 20px;
            line-height: 22px;
        }

        .nav {
            width: 100%;
            height: 30px;
            margin: 0 auto;
            background: #f00;
            position: fixed;
            bottom: 0;
            text-align: center;
        }
    </style>
</head>

<body onload="init()">
    <div id="container"></div>
    <div style="height:22px;"></div>
    <div id="fitBoundsDiv"></div>
    <div id="centerDiv"></div>
    <div id="zoomDiv"></div>
    <div id="containerDiv"></div>
    <div id="mapTypeIdDiv"></div>
    <div id="projection"></div>
    <div class="nav">导航</div>
    <script type="text/javascript">
        function init() {
            //div容器
            var container = document.getElementById("container");
            var centerDiv = document.getElementById("centerDiv");

            //初始化地图
            var map = new qq.maps.Map(container, {
                // 地图的中心地理坐标
                center: new qq.maps.LatLng(39.916527, 116.397128),
                zoom: 13,
                disableDefaultUI: true    //禁止所有控件
            });
          //创建自定义控件
            var middleControl = document.createElement("div");

            var height = document.body.scrollHeight;
            var marginTop = height / 2;       //因为此div在页面中只用了一次且以后不会改变，所以写了数值，如果是不确定的，获取到高度放着这里就可以
            middleControl.style.margin = marginTop+"px auto";
			middleControl.style.position="relative";
			middleControl.style.width="36px";
            middleControl.style.height="36px";
			middleControl.style.zIndex="100000";
           middleControl.innerHTML ='<img src="https://www.cdlhome.com.sg/mobile_assets/images/icon-location.png" />';
		   document.getElementById("container").appendChild(middleControl);
            //返回地图当前中心点地理坐标
            centerDiv.innerHTML = "latlng:" + map.getCenter();
            //当地图中心属性更改时触发事件
            qq.maps.event.addListener(map, 'center_changed', function() {
                centerDiv.innerHTML = "latlng:" + map.getCenter();
            });
        }
    </script>
</body>

</html>

src/paylive.Console/Views/Home/Index.cshtml
@model List<paylive.Console.DbContext.Receivers>
@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1"/>
    <!-- head 中 -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>

    </title>
    <!-- body 最后 -->

</head>
<body style="text-align: center">
<p>
    <a href="@Url.Action("Contact", "Home")">添加测试商户</a>
</p>
<form action="@Url.Action("Index", "Home")" method="post">

    <p>
        选择商户:<select id="imno" name="imno">
            @{
                foreach (var item in Model)
                {
                    <option value="@item.ImNo">@item.Mobile</option>
                }
            }
        </select>
    </p>
    <p>
        短信内容:<input type="text" id="msg" name="msg" style="height: 50px; width: 100px"/>
    </p>
    <p>
        <input type="submit" value="发送短信"/>
    </p>
</form>
</body>
</html>

src/paylive.Console/Views/Robot/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1" />
    <!-- head 中 -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>

    </title>
    <!-- body 最后 -->

</head>
<body style="text-align: center">
    <p><a href="@Url.Action("GetSmsPwd","Robot")">获取验证码</a></p>
    <form action="@Url.Action("Login", "Robot")" method="post">
        <p>
            验证码:<input type="text" id="pwd" name="pwd" style="height: 50px; width: 100px" />
        </p>
        <p>
            <input type="submit" value="登录" style="height: 50px; width: 100px" />
        </p>
    </form>
</body>
</html>

src/paylive.Console/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - paylive.Console</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">paylive.Console</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - paylive.Console</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>